"use strict";
/**
 * Mois de test : les 25 métiers ajoutés aux 5 d'origine (café, coiffeur, fleuriste, supérette, bar), pour 30 commerces
 * fictifs par ville. Même forme que TYPES / BANK dans testMonth.js : un nom par ville (même ordre que CITIES), une
 * description, 5 récompenses (paliers 1 à 5), et une banque de 16 questions (un commerce publie un jour sur deux, une
 * question reste ouverte 48 h : 16 questions couvrent un mois sans répétition).
 * Le secteur est choisi pour tomber dans le bon centre d'intérêt (sectorCategory, lib.js et app).
 */
const YN = ["Oui", "Peut-être", "Non"];

const TYPES = {
  restaurant: {
    sector: "Restaurant", emoji: "🍽️", interest: "restauration",
    names: ["Le Bistrot des Tilleuls", "La Table Buissonnière", "Le Petit Zinc Doré", "Chez Mamie Capucine", "La Cuillère Voyageuse", "Le Comptoir des Saisons", "L'Assiette Vagabonde", "La Marmite Enchantée", "Le Bouchon Rieur", "La Galette Gourmande"],
    desc: "Bistrot de quartier : cuisine maison, produits de saison et menu du jour le midi.",
    rewards: ["Café gourmand offert", "Dessert offert", "Entrée et dessert", "Menu du jour offert", "Repas pour deux"],
    bank: [
      ["Le midi, tu préfères…", ["Un menu du jour", "Une carte courte", "Un plat rapide à emporter"]],
      ["Un menu entrée-plat-dessert à 16 €, ça te paraît…", ["Raisonnable", "Un peu cher", "Trop cher"]],
      ["Tu aimerais plus d'options végétariennes ?", ["Oui", "Une ou deux suffisent", "Pas besoin"]],
      ["Tu viendrais pour un brunch le dimanche ?", YN],
      ["Quel dessert maison te ferait craquer ?", ["Tarte Tatin", "Mousse au chocolat", "Crème brûlée", "Île flottante"]],
      ["Tu réserves plutôt…", ["Par téléphone", "En ligne", "Je viens sans réserver"]],
      ["Une soirée à thème par mois, ça te tente ?", YN],
      ["Tu préfères une salle…", ["Calme", "Animée", "En terrasse", "Peu importe"]],
      ["Le service du midi devrait durer…", ["Moins de 45 min", "Environ 1 h", "Le temps qu'il faut"]],
      ["Tu commanderais nos plats à emporter le soir ?", YN],
      ["Quelle cuisine du monde aimerais-tu voir en plat du jour ?", ["Italienne", "Libanaise", "Indienne", "Mexicaine"]],
      ["Tu viens plutôt…", ["Seul", "Entre collègues", "En famille", "Entre amis"]],
      ["Un menu enfant, c'est important pour toi ?", ["Oui", "Parfois", "Pas concerné"]],
      ["Les produits locaux, ça compte pour toi ?", ["Beaucoup", "Un peu", "Pas vraiment"]],
      ["Tu aimerais connaître le menu de la semaine à l'avance ?", YN],
      ["Un atelier cuisine avec le chef, ça te plairait ?", YN],
    ],
  },
  pizzeria: {
    sector: "Pizzeria", emoji: "🍕", interest: "restauration",
    names: ["Pizza Lucciola", "Il Forno Felice", "La Bella Mozza", "Pizzeria Vesuvietto", "Napoli Nuvola", "La Pâte qui Chante", "Pizzeria Basilico", "Forno di Luna", "La Margherita Rêveuse", "Pizza Tramontana"],
    desc: "Pizzeria au feu de bois : pâte maturée 48 h, produits italiens, sur place ou à emporter.",
    rewards: ["Boisson offerte", "Tiramisu offert", "Pizza Margherita offerte", "Pizza au choix offerte", "Deux pizzas au choix"],
    bank: [
      ["Ta pizza préférée ?", ["Margherita", "Quatre fromages", "Reine", "Végétarienne"]],
      ["Tu manges plutôt sur place, à emporter ou en livraison ?", ["Sur place", "À emporter", "En livraison"]],
      ["Une pâte plutôt…", ["Fine et croustillante", "Épaisse et moelleuse", "Peu importe"]],
      ["Quelle pizza du moment aimerais-tu voir à la carte ?", ["Truffe", "Burrata", "Chèvre-miel", "Pesto"]],
      ["Une pizza à 13 €, ça te paraît…", ["Raisonnable", "Un peu cher", "Trop cher"]],
      ["Tu aimerais une formule midi (pizza + boisson) ?", YN],
      ["Tu commandes plutôt…", ["Par téléphone", "En ligne", "Sur place"]],
      ["Une pizza sans gluten, ça t'intéresserait ?", ["Oui", "Pour un proche", "Non"]],
      ["Quel dessert italien te ferait plaisir ?", ["Tiramisu", "Panna cotta", "Cannoli", "Glace"]],
      ["Tu viens surtout…", ["Le midi", "Le soir en semaine", "Le week-end"]],
      ["Tu aimerais composer ta pizza toi-même ?", YN],
      ["Une soirée « pizza à volonté », ça te tente ?", YN],
      ["Les produits italiens importés, c'est important pour toi ?", ["Oui", "Un peu", "Pas vraiment"]],
      ["Tu préfères une part ou une pizza entière ?", ["Une part", "Une entière", "Ça dépend"]],
      ["Un atelier pizza pour les enfants, ça te plairait ?", ["Oui", "Peut-être", "Pas concerné"]],
      ["Le temps d'attente idéal pour une pizza à emporter ?", ["Moins de 10 min", "10 à 20 min", "Peu importe"]],
    ],
  },
  sushi: {
    sector: "Restaurant japonais", emoji: "🍣", interest: "restauration",
    names: ["Sakura Komorebi", "Maki Hoshi", "Le Jardin d'Edo", "Wasabi Lune", "Umami Kaze", "Hana Bento", "Nori & Riz", "Kumo Sushi", "Tatami Doré", "Sushi Mirai"],
    desc: "Restaurant japonais : sushis, ramens et bentos préparés à la minute.",
    rewards: ["Soupe miso offerte", "Mochi offert", "Plateau de makis", "Bento offert", "Plateau pour deux"],
    bank: [
      ["Tu préfères…", ["Sushis", "Makis", "Ramen", "Bento"]],
      ["Tu manges plutôt sur place ou à emporter ?", ["Sur place", "À emporter", "En livraison"]],
      ["Un plateau de 18 pièces à 16 €, ça te paraît…", ["Raisonnable", "Un peu cher", "Trop cher"]],
      ["Tu aimerais des ramens le soir en hiver ?", YN],
      ["Quel poisson préfères-tu ?", ["Saumon", "Thon", "Daurade", "Je mange végétarien"]],
      ["Une formule midi rapide (bento + boisson), ça t'intéresse ?", YN],
      ["Tu goûterais des sushis végétariens ?", YN],
      ["Quel dessert japonais te tente ?", ["Mochi", "Dorayaki", "Glace au matcha", "Aucun"]],
      ["Tu aimerais un atelier « faire ses makis » ?", YN],
      ["Tu viens plutôt…", ["Seul", "À deux", "En groupe"]],
      ["Un thé japonais offert avec le repas, ça compte pour toi ?", ["Oui", "Un petit plus", "Pas du tout"]],
      ["Tu commandes plutôt…", ["Sur place", "Par téléphone", "En ligne"]],
      ["Le riz complet à la place du riz blanc, ça t'intéresse ?", YN],
      ["Tu préfères un poisson…", ["Cru", "Mi-cuit", "Cuit", "Peu importe"]],
      ["Une soirée dégustation de saké sans alcool ou de thés, ça te tente ?", YN],
      ["Tu viendrais pour un plat du jour japonais le midi ?", YN],
    ],
  },
  burger: {
    sector: "Snack burger", emoji: "🍔", interest: "restauration",
    names: ["Burger Comète", "Le Bun Malin", "Smash & Cie", "Le Cheddar Volant", "Burger Lanterne", "La Frite Joyeuse", "Big Bun Boréal", "Le Steak Rieur", "Burger Phare Ouest", "Le Bun Breton"],
    desc: "Burgers maison : pain brioché du boulanger voisin, frites fraîches, options végétariennes.",
    rewards: ["Frites offertes", "Boisson et frites", "Burger offert", "Menu burger offert", "Deux menus burger"],
    bank: [
      ["Ton burger idéal ?", ["Classique", "Au poulet", "Végétarien", "Avec du fromage fondant"]],
      ["Tes frites, tu les préfères…", ["Fines", "Épaisses", "Patate douce"]],
      ["Un menu burger à 13 €, ça te paraît…", ["Raisonnable", "Un peu cher", "Trop cher"]],
      ["Tu manges plutôt sur place ou à emporter ?", ["Sur place", "À emporter", "En livraison"]],
      ["Tu aimerais un burger du mois ?", YN],
      ["Quelle sauce maison manque à notre carte ?", ["Barbecue", "Fromagère", "Poivre", "Curry doux"]],
      ["Une option sans gluten, ça t'intéresse ?", ["Oui", "Pour un proche", "Non"]],
      ["Tu viens surtout…", ["Le midi", "Le soir", "Le week-end"]],
      ["Un milkshake maison, ça te tente ?", YN],
      ["Tu préfères une viande…", ["Bien cuite", "À point", "Saignante", "Pas de viande"]],
      ["Une offre étudiante te ferait venir plus souvent ?", ["Oui", "Peut-être", "Pas concerné"]],
      ["Tu commandes plutôt…", ["Au comptoir", "Sur une borne", "En ligne"]],
      ["Un dessert maison, tu le prendrais ?", ["Cookie", "Brownie", "Glace", "Pas de dessert"]],
      ["Le pain brioché ou le pain classique ?", ["Brioché", "Classique", "Peu importe"]],
      ["Tu aimerais une formule enfant ?", ["Oui", "Peut-être", "Pas concerné"]],
      ["Une carte de fidélité (10e menu offert), ça te motiverait ?", YN],
    ],
  },
  creperie: {
    sector: "Crêperie", emoji: "🥞", interest: "restauration",
    names: ["La Bilig Joyeuse", "Crêpe & Clapotis", "Le Blé Noir Doré", "La Galette du Phare", "Crêperie Kouign Lune", "Le Sarrasin Rêveur", "La Crêpe Voyageuse", "Ty Crampouez", "La Beurrée Salée", "Crêperie Menhir"],
    desc: "Crêperie : galettes de sarrasin, crêpes sucrées et cidre doux, à déguster ou à emporter.",
    rewards: ["Crêpe sucre offerte", "Crêpe au choix", "Galette complète", "Formule galette et crêpe", "Formule pour deux"],
    bank: [
      ["Ta galette préférée ?", ["Complète", "Chèvre-miel", "Saucisse", "Forestière"]],
      ["Ta crêpe sucrée préférée ?", ["Beurre-sucre", "Caramel beurre salé", "Chocolat", "Confiture"]],
      ["Une formule galette + crêpe à 14 €, ça te paraît…", ["Raisonnable", "Un peu cher", "Trop cher"]],
      ["Tu viendrais pour un goûter crêpes l'après-midi ?", YN],
      ["Tu préfères…", ["Sur place", "À emporter", "Les deux"]],
      ["Une galette du mois, ça te tente ?", YN],
      ["Tu aimerais une galette végétarienne de plus ?", YN],
      ["Tu viens plutôt…", ["Le midi", "Le soir", "Le week-end", "Au goûter"]],
      ["Un atelier « faire ses crêpes » pour les enfants ?", ["Oui", "Peut-être", "Pas concerné"]],
      ["Le sarrasin sans gluten, c'est important pour toi ?", ["Oui", "Un peu", "Pas du tout"]],
      ["Quelle boisson avec ta galette ?", ["Jus de pomme", "Lait ribot", "Thé", "Eau"]],
      ["Une crêpe glacée l'été, ça te plairait ?", YN],
      ["Tu préfères une ambiance…", ["Bretonne traditionnelle", "Moderne", "Peu importe"]],
      ["Tu commanderais des crêpes pour un anniversaire ?", YN],
      ["Une carte de fidélité, tu la préfères…", ["Sur papier", "Sur téléphone", "Pas besoin"]],
      ["La Chandeleur, tu aimerais une animation spéciale ?", YN],
    ],
  },
  boulangerie: {
    sector: "Boulangerie", emoji: "🥖", interest: "boulangerie",
    names: ["Au Pain Funambule", "La Mie Câline", "Le Fournil des Lucioles", "Boulangerie Épi d'Or", "Le Levain Rieur", "La Croûte Dorée", "Au Blé Tendre", "Le Pétrin Voyageur", "La Baguette Lunaire", "Le Four à Bois Breton"],
    desc: "Boulangerie artisanale : pains au levain, viennoiseries pur beurre et snacking du midi.",
    rewards: ["Baguette offerte", "Viennoiserie offerte", "Formule sandwich", "Gâteau individuel et pain", "Grand gâteau à partager"],
    bank: [
      ["Ta baguette, tu la préfères…", ["Bien cuite", "Pas trop cuite", "Tradition", "Classique"]],
      ["À quelle heure passes-tu le plus souvent ?", ["Avant 8h", "8h-10h", "Le midi", "En fin de journée"]],
      ["Tu aimerais plus de pains spéciaux ?", ["Céréales", "Seigle", "Épeautre", "Ça me va comme ça"]],
      ["Une formule sandwich le midi à 7 €, ça te paraît…", ["Raisonnable", "Un peu cher", "Trop cher"]],
      ["Tu réserverais ton pain la veille ?", YN],
      ["Quelle viennoiserie manque à notre vitrine ?", ["Pain aux raisins", "Chausson aux pommes", "Brioche suisse", "Kouign-amann"]],
      ["Le dimanche, tu passes…", ["Le matin", "Pas le dimanche", "Ça dépend"]],
      ["Un pain sans gluten, ça t'intéresserait ?", ["Oui", "Pour un proche", "Non"]],
      ["Tu préfères payer…", ["En espèces", "Par carte", "Avec le téléphone"]],
      ["Une galette des rois maison en janvier, tu la commanderais ?", YN],
      ["Tu aimerais des produits du jour à prix réduit le soir ?", YN],
      ["Le pain bio, c'est important pour toi ?", ["Oui", "Un peu", "Pas vraiment"]],
      ["Quel snack salé te manque le midi ?", ["Quiche", "Pizza", "Croque", "Salade"]],
      ["Un atelier « faire son pain » le samedi, ça te tente ?", YN],
      ["Tu achètes plutôt…", ["Une baguette", "Plusieurs pains", "Viennoiseries surtout"]],
      ["Une carte de fidélité, ça te motiverait ?", YN],
    ],
  },
  patisserie: {
    sector: "Pâtisserie", emoji: "🍰", interest: "boulangerie",
    names: ["Sucre & Nuage", "La Pâtisserie Hirondelle", "Le Fraisier Céleste", "Choux Bijoux", "La Meringue Rêveuse", "Pâtisserie Praline", "L'Éclair Voyageur", "Le Macaron Bleu", "La Tarte Étoilée", "Le Far Doré"],
    desc: "Pâtisserie fine : entremets, macarons et gâteaux de fête sur commande.",
    rewards: ["Macaron offert", "Pâtisserie individuelle", "Boîte de 6 macarons", "Entremets individuel et café", "Gâteau pour 6 personnes"],
    bank: [
      ["Ta pâtisserie préférée ?", ["Éclair", "Tarte au citron", "Fraisier", "Paris-Brest"]],
      ["Tu achètes des pâtisseries…", ["Chaque semaine", "Pour les occasions", "Rarement"]],
      ["Une pâtisserie individuelle à 5 €, ça te paraît…", ["Raisonnable", "Un peu cher", "Trop cher"]],
      ["Tu aimerais des pâtisseries moins sucrées ?", YN],
      ["Quel parfum de macaron te manque ?", ["Pistache", "Framboise", "Caramel", "Citron"]],
      ["Tu commanderais un gâteau d'anniversaire chez nous ?", YN],
      ["Un salon de thé pour déguster sur place, ça te plairait ?", YN],
      ["Tu préfères les pâtisseries…", ["Classiques", "Créatives", "Les deux"]],
      ["Une pâtisserie sans gluten, ça t'intéresserait ?", ["Oui", "Pour un proche", "Non"]],
      ["Tu viendrais à un atelier macarons ?", YN],
      ["Pour un repas de famille, tu prends plutôt…", ["Un grand gâteau", "Des parts individuelles", "Des mignardises"]],
      ["Les fruits de saison dans les desserts, c'est important ?", ["Très", "Un peu", "Pas vraiment"]],
      ["Tu commandes plutôt…", ["En boutique", "Par téléphone", "En ligne"]],
      ["Une bûche de Noël maison, tu la réserverais ?", YN],
      ["Le dimanche matin, tu passes ?", ["Oui", "Parfois", "Non"]],
      ["Une pâtisserie du mois, ça te donnerait envie de revenir ?", YN],
    ],
  },
  chocolatier: {
    sector: "Chocolatier", emoji: "🍫", interest: "boulangerie",
    names: ["Cacao Comète", "La Fève Rieuse", "Chocolat Hirondelle", "Le Praliné Doré", "Ganache & Lune", "La Tablette Voyageuse", "Cabosse Bleue", "Le Bonbon de Chocolat", "Maison Grué", "Chocolaterie Galet"],
    desc: "Chocolatier artisan : tablettes, bonbons de chocolat et créations de saison.",
    rewards: ["Bonbon de chocolat offert", "Mendiant offert", "Tablette au choix", "Ballotin 250 g", "Grand coffret de saison"],
    bank: [
      ["Tu préfères le chocolat…", ["Noir", "Au lait", "Blanc", "Tous"]],
      ["Tu achètes du chocolat…", ["Pour moi", "Pour offrir", "Les deux"]],
      ["Une tablette artisanale à 6 €, ça te paraît…", ["Raisonnable", "Un peu cher", "Trop cher"]],
      ["Quelle garniture préfères-tu ?", ["Praliné", "Ganache", "Caramel", "Fruits"]],
      ["Le chocolat bio ou équitable, ça compte pour toi ?", ["Beaucoup", "Un peu", "Pas vraiment"]],
      ["Tu viendrais à une dégustation de chocolats ?", YN],
      ["Un chocolat chaud à emporter l'hiver, ça te tente ?", YN],
      ["Pour Pâques, tu prends plutôt…", ["Des œufs", "Des petites fritures", "Un sujet", "Rien"]],
      ["Un coffret personnalisé pour offrir, ça t'intéresse ?", YN],
      ["Tu préfères un chocolat…", ["Très cacaoté", "Doux", "Ça dépend"]],
      ["Un atelier chocolat pour les enfants, ça te plairait ?", ["Oui", "Peut-être", "Pas concerné"]],
      ["Tu passes plutôt…", ["En semaine", "Le week-end", "Aux fêtes"]],
      ["Des chocolats moins sucrés, ça te tenterait ?", YN],
      ["Une tablette du mois aux saveurs originales ?", YN],
      ["Tu commanderais en ligne pour retirer en boutique ?", YN],
      ["Ton parfum préféré ?", ["Noisette", "Orange", "Framboise", "Café"]],
    ],
  },
  fitness: {
    sector: "Salle de sport", emoji: "🏋️", interest: "sport",
    names: ["Atelier Forme Comète", "Gym Hirondelle", "Le Club Énergie Bleue", "Fit & Lune", "Salle Élan Vif", "Le Studio Rebond", "Gym du Phare", "Forme Boréale", "Le Club Cardio Doux", "Breizh Fit"],
    desc: "Salle de sport de quartier : musculation, cardio et cours collectifs encadrés.",
    rewards: ["Séance d'essai offerte", "Boisson protéinée", "Cours collectif offert", "Semaine d'accès offerte", "Mois d'abonnement offert"],
    bank: [
      ["Quand préfères-tu t'entraîner ?", ["Tôt le matin", "Le midi", "Le soir", "Le week-end"]],
      ["Quel cours collectif te tente le plus ?", ["Cross-training", "Pilates", "Zumba", "Renforcement"]],
      ["Un abonnement à 30 € par mois, ça te paraît…", ["Raisonnable", "Un peu cher", "Trop cher"]],
      ["Tu préfères t'entraîner…", ["Seul", "En cours collectif", "Avec un coach"]],
      ["Une séance de coaching découverte, ça t'intéresse ?", YN],
      ["Tu fais du sport…", ["Plusieurs fois par semaine", "Une fois par semaine", "Rarement", "Jamais"]],
      ["Qu'est-ce qui te ferait venir plus souvent ?", ["Plus de cours", "Horaires plus larges", "Un prix plus bas", "Un programme suivi"]],
      ["Un espace de garde d'enfants, ce serait utile ?", ["Oui", "Peut-être", "Pas concerné"]],
      ["Tu aimerais des cours en extérieur l'été ?", YN],
      ["Ton objectif principal ?", ["Forme", "Perte de poids", "Muscle", "Détente"]],
      ["Un abonnement sans engagement, c'est important ?", ["Très", "Un peu", "Pas du tout"]],
      ["Tu réserverais tes cours sur une appli ?", YN],
      ["Un sauna ou un espace détente, ça compte pour toi ?", ["Oui", "Un plus", "Pas du tout"]],
      ["Un défi sportif entre membres chaque mois ?", YN],
      ["Tu viens plutôt…", ["Seul", "Avec un ami", "En couple"]],
      ["Des conseils nutrition, ça t'intéresserait ?", YN],
    ],
  },
  yoga: {
    sector: "Studio de yoga", emoji: "🧘", interest: "sport",
    names: ["Lotus Nuage", "Le Souffle Doux", "Studio Asana Lune", "Om & Tilleul", "La Posture Vagabonde", "Shanti Comète", "Le Tapis Rêveur", "Prana Boréal", "Yoga des Hiboux", "Respire Iroise"],
    desc: "Studio de yoga et de pilates : cours tous niveaux, petits groupes, ambiance calme.",
    rewards: ["Thé offert après le cours", "Cours découverte", "Cours au choix offert", "Carte 5 cours", "Mois illimité offert"],
    bank: [
      ["Quel type de yoga te tente ?", ["Doux", "Dynamique", "Yin", "Je découvre"]],
      ["Ton créneau idéal ?", ["Tôt le matin", "Pause déjeuner", "En soirée", "Le week-end"]],
      ["Un cours à 15 €, ça te paraît…", ["Raisonnable", "Un peu cher", "Trop cher"]],
      ["Tu préfères un cours de…", ["45 min", "1 h", "1 h 30"]],
      ["Un atelier méditation, ça t'intéresse ?", YN],
      ["Tu as déjà fait du yoga ?", ["Souvent", "Un peu", "Jamais"]],
      ["Le pilates, ça te tenterait ?", YN],
      ["Des cours en ligne en complément, ce serait utile ?", YN],
      ["Un cours parent-enfant, ça te plairait ?", ["Oui", "Peut-être", "Pas concerné"]],
      ["Tu préfères un groupe…", ["Petit (moins de 8)", "Moyen", "Peu importe"]],
      ["Une retraite d'une journée, ça te tente ?", YN],
      ["Ce qui compte le plus pour toi ?", ["Le professeur", "L'ambiance", "Les horaires", "Le prix"]],
      ["Du yoga en plein air l'été ?", YN],
      ["Un cours spécial dos et posture ?", YN],
      ["Tu viendrais avec ton propre tapis ?", ["Oui", "Je préfère en emprunter", "Peu importe"]],
      ["Une carte de cours valable plusieurs mois, ça t'arrange ?", YN],
    ],
  },
  velo: {
    sector: "Magasin de vélos", emoji: "🚲", interest: "sport",
    names: ["Cycles Hirondelle", "Le Rayon Vert", "Vélo Comète", "La Roue Libre Bleue", "Cycles du Phare", "Le Guidon Rieur", "Pédale & Lune", "L'Atelier Dérailleur", "Cycles Boussole", "Vélo Korrigan"],
    desc: "Magasin et atelier vélo : réparations rapides, vélos de ville et électriques, location.",
    rewards: ["Gonflage et réglage offerts", "Accessoire offert", "Révision express", "Révision complète", "Journée de location offerte"],
    bank: [
      ["Tu utilises ton vélo pour…", ["Aller au travail", "Les loisirs", "Le sport", "Je n'ai pas de vélo"]],
      ["Un vélo électrique, ça te tente ?", ["Oui", "Peut-être", "Non"]],
      ["Une révision complète à 60 €, ça te paraît…", ["Raisonnable", "Un peu cher", "Trop cher"]],
      ["Tu fais réviser ton vélo…", ["Chaque année", "Quand il casse", "Jamais"]],
      ["Une réparation pendant que tu attends, c'est important ?", ["Très", "Un peu", "Pas du tout"]],
      ["La location de vélos à la journée, ça t'intéresse ?", YN],
      ["Un atelier « réparer soi-même », ça te plairait ?", YN],
      ["Quel accessoire te manque ?", ["Antivol", "Éclairage", "Sacoche", "Casque"]],
      ["Tu achèterais un vélo d'occasion révisé ?", YN],
      ["Une balade à vélo organisée le dimanche ?", YN],
      ["Le stationnement vélo sécurisé, ça manque dans ton quartier ?", ["Oui", "Un peu", "Non"]],
      ["Tu prendrais rendez-vous en ligne pour une réparation ?", YN],
      ["Un vélo pour enfant à louer, ce serait utile ?", ["Oui", "Peut-être", "Pas concerné"]],
      ["Le vélo cargo, ça te tente ?", YN],
      ["Ce qui te freine pour faire plus de vélo ?", ["La météo", "La sécurité", "La distance", "Rien"]],
      ["Un forfait entretien à l'année, ça t'intéresse ?", YN],
    ],
  },
  barbier: {
    sector: "Barbier", emoji: "💈", interest: "beaute",
    names: ["Le Blaireau Doré", "Barbe & Boussole", "L'Atelier Moustache", "Barber Comète", "Le Rasoir Rieur", "La Barbe Voyageuse", "Barbier du Phare", "Le Coupe-Chou Bleu", "Barbe Boréale", "Le Barbier d'Armor"],
    desc: "Barbier : coupes homme, taille de barbe à l'ancienne et soins du visage.",
    rewards: ["Contour de barbe offert", "Soin barbe offert", "Taille de barbe offerte", "Coupe offerte", "Coupe et barbe offertes"],
    bank: [
      ["Tu viens plutôt pour…", ["La coupe", "La barbe", "Les deux"]],
      ["Ton créneau idéal ?", ["Tôt le matin", "Pause déjeuner", "Après 18h", "Le samedi"]],
      ["Une taille de barbe à 15 €, ça te paraît…", ["Raisonnable", "Un peu cher", "Trop cher"]],
      ["Tu préfères avec ou sans rendez-vous ?", ["Rendez-vous", "Sans rendez-vous", "Les deux"]],
      ["Le rasage à l'ancienne (serviette chaude), ça te tente ?", YN],
      ["Tu passes tous les…", ["15 jours", "Mois", "2 mois", "Rarement"]],
      ["Une huile ou un baume pour la barbe, tu en utilises ?", ["Oui", "Parfois", "Jamais"]],
      ["Un forfait mensuel (coupe + barbe), ça t'intéresse ?", YN],
      ["Ce qui compte le plus pour toi ?", ["Le résultat", "La rapidité", "L'ambiance", "Le prix"]],
      ["Une coupe enfant chez le barbier, ce serait utile ?", ["Oui", "Peut-être", "Pas concerné"]],
      ["Tu réserverais en ligne ?", YN],
      ["Un soin du visage homme, ça te tenterait ?", YN],
      ["Quelle coupe te tente ?", ["Dégradé", "Classique", "Longueur sur le dessus", "Je garde mon style"]],
      ["Une boisson offerte pendant l'attente, c'est un plus ?", ["Oui", "Un petit plus", "Pas du tout"]],
      ["Tu viens plutôt…", ["Seul", "Avec un ami", "Avec mon fils"]],
      ["Une carte de fidélité, ça te motiverait ?", YN],
    ],
  },
  institut: {
    sector: "Institut d'esthétique", emoji: "💆", interest: "beaute",
    names: ["L'Institut Pétale", "Bulle de Soie", "Le Jardin de Peau", "Éclat de Lune", "Institut Douceur Bleue", "La Parenthèse Rose", "Beauté Hirondelle", "Le Cocon Doré", "Institut Nacre", "Belle-Île Beauté"],
    desc: "Institut de beauté : soins du visage, épilations et modelages relaxants.",
    rewards: ["Diagnostic de peau offert", "Pose de vernis offerte", "Soin express du visage", "Soin du visage complet", "Modelage d'une heure"],
    bank: [
      ["Quel soin te ferait le plus plaisir ?", ["Soin du visage", "Modelage", "Épilation", "Manucure"]],
      ["Ton créneau idéal ?", ["En semaine en journée", "Après 18h", "Le samedi"]],
      ["Un soin du visage à 45 €, ça te paraît…", ["Raisonnable", "Un peu cher", "Trop cher"]],
      ["Tu viens à l'institut…", ["Chaque mois", "Quelques fois par an", "Pour les occasions", "Jamais"]],
      ["Les produits naturels ou bio, c'est important ?", ["Très", "Un peu", "Pas vraiment"]],
      ["Un carnet de soins à prix réduit, ça t'intéresse ?", YN],
      ["Tu réserverais en ligne ?", YN],
      ["Des soins pour homme, ce serait utile ?", ["Oui", "Peut-être", "Pas concerné"]],
      ["Un bon cadeau pour offrir, tu en achèterais ?", YN],
      ["Ce qui compte le plus pour toi ?", ["Le calme", "Le résultat", "Le prix", "Les horaires"]],
      ["Un soin duo (à deux), ça te tente ?", YN],
      ["Un conseil maquillage personnalisé ?", YN],
      ["Tu préfères un soin de…", ["30 min", "1 h", "Plus d'1 h"]],
      ["Une soirée détente entre amies à l'institut ?", YN],
      ["Un rappel par SMS avant ton rendez-vous, c'est utile ?", YN],
      ["Des soins pour peaux sensibles, ça t'intéresse ?", YN],
    ],
  },
  onglerie: {
    sector: "Onglerie", emoji: "💅", interest: "beaute",
    names: ["Ongles & Étoiles", "Vernis Comète", "La Manucure Rieuse", "Nail Lune", "L'Ongle Doré", "Le Bar à Vernis", "Pastel Nails", "Ongle de Soie", "Paillette & Cie", "Nacre & Ongles"],
    desc: "Onglerie : manucure, pose de vernis semi-permanent et nail art.",
    rewards: ["Limage et vernis offerts", "French manucure", "Semi-permanent mains", "Manucure complète", "Mains et pieds"],
    bank: [
      ["Tu préfères…", ["Vernis classique", "Semi-permanent", "Gel", "Ongles naturels"]],
      ["Une pose de semi-permanent à 30 €, ça te paraît…", ["Raisonnable", "Un peu cher", "Trop cher"]],
      ["Tu viens tous les…", ["2 semaines", "3-4 semaines", "Pour les occasions", "Rarement"]],
      ["Le nail art, ça te tente ?", ["Oui, carrément", "Discret", "Non"]],
      ["Ta couleur du moment ?", ["Nude", "Rouge", "Pastel", "Foncé"]],
      ["Avec ou sans rendez-vous ?", ["Rendez-vous", "Sans rendez-vous", "Les deux"]],
      ["Les vernis sans produits toxiques, c'est important ?", ["Très", "Un peu", "Pas vraiment"]],
      ["Une beauté des pieds, ça t'intéresse ?", YN],
      ["Un forfait mensuel, ça te motiverait ?", YN],
      ["Ton créneau idéal ?", ["Pause déjeuner", "Après 18h", "Le samedi"]],
      ["Une séance à deux entre amies ?", YN],
      ["Un soin des mains hydratant en plus ?", YN],
      ["Tu réserverais en ligne ?", YN],
      ["Tu choisis ton modèle…", ["Avec une photo", "Sur conseil", "Toujours le même"]],
      ["Une pose express de 20 minutes, ça t'intéresse ?", YN],
      ["Une carte de fidélité, ça te motiverait ?", YN],
    ],
  },
  librairie: {
    sector: "Librairie", emoji: "📚", interest: "culture",
    names: ["La Page Vagabonde", "Le Marque-Page Bleu", "Librairie Hirondelle", "Les Mots Voyageurs", "La Plume Rieuse", "Le Chapitre Doré", "Librairie Comète", "L'Encre Lunaire", "Le Livre Funambule", "Librairie Ar Levrioù"],
    desc: "Librairie indépendante : romans, BD, jeunesse et conseils de libraires passionnés.",
    rewards: ["Marque-page collector", "Carnet offert", "Livre de poche offert", "BD au choix", "Beau livre au choix"],
    bank: [
      ["Tu lis surtout…", ["Romans", "BD et mangas", "Essais", "Jeunesse"]],
      ["Tu achètes un livre…", ["Chaque semaine", "Chaque mois", "Quelques fois par an", "Rarement"]],
      ["Une rencontre avec un auteur, ça te tente ?", YN],
      ["Tu commanderais un livre pour le retirer en boutique ?", YN],
      ["Un club de lecture mensuel, ça t'intéresse ?", YN],
      ["Quel rayon aimerais-tu voir plus grand ?", ["Polars", "Science-fiction", "Mangas", "Cuisine"]],
      ["Les conseils du libraire, tu les suis ?", ["Souvent", "Parfois", "Jamais"]],
      ["Des livres d'occasion en rayon, ça te plairait ?", YN],
      ["Une heure du conte pour les enfants le mercredi ?", ["Oui", "Peut-être", "Pas concerné"]],
      ["Tu lis plutôt…", ["Le soir", "Dans les transports", "Le week-end", "En vacances"]],
      ["Un coin café pour lire sur place ?", YN],
      ["Tu offres des livres ?", ["Souvent", "Parfois", "Jamais"]],
      ["Les livres audio, tu en écoutes ?", ["Oui", "Parfois", "Jamais"]],
      ["Une sélection « coups de cœur » chaque mois, ça t'aide ?", YN],
      ["Ce qui te ferait venir plus souvent ?", ["Plus d'événements", "Une carte fidélité", "Des horaires plus larges", "Plus de choix"]],
      ["Un emballage cadeau offert, c'est important ?", ["Oui", "Un plus", "Pas du tout"]],
    ],
  },
  cinema: {
    sector: "Cinéma de quartier", emoji: "🎬", interest: "culture",
    names: ["Le Ciné Lucioles", "Cinéma Hirondelle", "L'Écran Rêveur", "Le Studio Comète", "Ciné du Phare", "La Bobine Bleue", "Le Projecteur Doré", "Ciné Lune", "Le Rideau Rouge", "Ciné Korrigan"],
    desc: "Cinéma de quartier : films récents, ciné-débats et séances pour les enfants.",
    rewards: ["Pop-corn offert", "Boisson et pop-corn", "Place de cinéma offerte", "Deux places offertes", "Carte 5 places"],
    bank: [
      ["Quel genre de film préfères-tu ?", ["Comédie", "Action", "Drame", "Animation"]],
      ["Tu vas au cinéma…", ["Chaque semaine", "Chaque mois", "Quelques fois par an", "Rarement"]],
      ["Une place à 9 €, ça te paraît…", ["Raisonnable", "Un peu cher", "Trop cher"]],
      ["Ton jour préféré pour une séance ?", ["En semaine", "Le vendredi soir", "Le week-end"]],
      ["Les films en version originale, tu les choisis ?", ["Toujours", "Parfois", "Jamais"]],
      ["Un ciné-débat après le film, ça te tente ?", YN],
      ["Une séance spéciale enfants le mercredi ?", ["Oui", "Peut-être", "Pas concerné"]],
      ["Tu réserves ta place…", ["En ligne", "Sur place", "Peu importe"]],
      ["Une nuit du cinéma (3 films), ça te plairait ?", YN],
      ["La reprise de films cultes, ça t'intéresse ?", YN],
      ["Tu viens plutôt…", ["Seul", "En couple", "Entre amis", "En famille"]],
      ["Une carte d'abonnement, ça te motiverait ?", YN],
      ["Ce qui compte le plus ?", ["Le confort", "Le prix", "Le choix de films", "Les horaires"]],
      ["Une séance en matinée le dimanche ?", YN],
      ["Les avant-premières, ça te tente ?", YN],
      ["Un bar ou un café dans le cinéma, ça t'intéresse ?", YN],
    ],
  },
  disquaire: {
    sector: "Disquaire", emoji: "💿", interest: "culture",
    names: ["Le Microsillon", "Vinyle Comète", "La Platine Bleue", "Le Sillon Rêveur", "Disques Hirondelle", "Le 33 Tours Doré", "La Face B", "Groove Lune", "Le Diamant Funambule", "Disques d'Armor"],
    desc: "Disquaire : vinyles neufs et d'occasion, platines et écoute sur place.",
    rewards: ["Badge collector", "Sac en tissu", "Vinyle d'occasion au choix", "Vinyle neuf au choix", "Platine en location un mois"],
    bank: [
      ["Quel style écoutes-tu le plus ?", ["Pop", "Rap", "Rock", "Jazz"]],
      ["Tu écoutes de la musique…", ["Sur vinyle", "En streaming", "Les deux"]],
      ["Un vinyle neuf à 25 €, ça te paraît…", ["Raisonnable", "Un peu cher", "Trop cher"]],
      ["Les vinyles d'occasion, ça t'intéresse ?", YN],
      ["Une écoute sur place avant d'acheter, c'est important ?", ["Très", "Un peu", "Pas du tout"]],
      ["Un concert acoustique en boutique, ça te tente ?", YN],
      ["Tu revendrais tes vieux disques ?", YN],
      ["Tu possèdes une platine ?", ["Oui", "Non, mais j'aimerais", "Non"]],
      ["Une soirée « apporte tes vinyles », ça te plairait ?", YN],
      ["Les rééditions d'albums cultes, tu en achètes ?", ["Souvent", "Parfois", "Jamais"]],
      ["Les artistes locaux en rayon, ça t'intéresse ?", YN],
      ["Tu offres des vinyles ?", ["Souvent", "Parfois", "Jamais"]],
      ["Une réservation des nouveautés, ce serait utile ?", YN],
      ["Ton format préféré ?", ["Vinyle", "CD", "Cassette", "Numérique"]],
      ["Des conseils pour débuter une collection ?", YN],
      ["Une carte de fidélité, ça te motiverait ?", YN],
    ],
  },
  jeux: {
    sector: "Boutique de jeux", emoji: "🎲", interest: "culture",
    names: ["Le Dé Rieur", "La Ludo Comète", "Jeux & Lucioles", "Le Pion Voyageur", "La Partie Bleue", "Le Plateau Doré", "Meeple Lune", "Le Repaire des Joueurs", "La Carte Funambule", "Jeux du Phare"],
    desc: "Boutique de jeux de société : conseils, soirées jeux et coin pour jouer sur place.",
    rewards: ["Boisson pendant une partie", "Accès soirée jeux", "Petit jeu de cartes", "Jeu de société au choix", "Grand jeu de plateau"],
    bank: [
      ["Tu joues plutôt à…", ["Jeux de société", "Jeux de cartes", "Jeux de rôle", "Jeux vidéo"]],
      ["Tu joues…", ["En famille", "Entre amis", "En couple", "En club"]],
      ["Un jeu de société à 30 €, ça te paraît…", ["Raisonnable", "Un peu cher", "Trop cher"]],
      ["Une soirée jeux le vendredi, ça te tente ?", YN],
      ["Tu aimerais essayer un jeu avant de l'acheter ?", YN],
      ["Quel type de jeu préfères-tu ?", ["Coopératif", "Stratégie", "Ambiance", "Enquête"]],
      ["Un tournoi entre joueurs du quartier ?", YN],
      ["La location de jeux, ça t'intéresse ?", YN],
      ["Des jeux pour les tout-petits, ce serait utile ?", ["Oui", "Peut-être", "Pas concerné"]],
      ["Une partie dure idéalement…", ["Moins de 30 min", "30 min à 1 h", "Plus d'1 h"]],
      ["Les conseils du vendeur, tu les suis ?", ["Souvent", "Parfois", "Jamais"]],
      ["Un après-midi jeux pour les enfants le mercredi ?", ["Oui", "Peut-être", "Pas concerné"]],
      ["Tu offres des jeux ?", ["Souvent", "Parfois", "Jamais"]],
      ["Un coin pour jouer sur place avec boissons ?", YN],
      ["Un club de jeu de rôle, ça te tenterait ?", YN],
      ["Une carte de fidélité, ça te motiverait ?", YN],
    ],
  },
  fromagerie: {
    sector: "Fromagerie", emoji: "🧀", interest: "commerce",
    names: ["La Meule Rieuse", "Fromagerie Hirondelle", "Le Comté Doré", "La Tomme Voyageuse", "Au Bon Affinage", "Le Caillé Bleu", "Fromagerie Comète", "La Croûte Fleurie", "Le Chèvre Lunaire", "La Crémerie d'Armor"],
    desc: "Fromagerie : fromages affinés sur place, produits laitiers fermiers et plateaux sur commande.",
    rewards: ["Dégustation offerte", "Beurre fermier offert", "Morceau de fromage du mois", "Assortiment 3 fromages", "Plateau pour 6 personnes"],
    bank: [
      ["Ton fromage préféré ?", ["Pâte molle", "Pâte dure", "Chèvre", "Bleu"]],
      ["Tu achètes du fromage…", ["Chaque semaine", "Chaque mois", "Pour les occasions"]],
      ["Le fromage au lait cru, tu en manges ?", ["Oui", "Parfois", "Non"]],
      ["Un plateau sur commande pour un repas, ça t'intéresse ?", YN],
      ["Une dégustation commentée, ça te tente ?", YN],
      ["Les produits fermiers locaux, c'est important ?", ["Très", "Un peu", "Pas vraiment"]],
      ["Tu aimerais des fromages à la coupe en petites portions ?", YN],
      ["Quel produit laitier te manque ?", ["Yaourts fermiers", "Crème crue", "Beurre salé", "Faisselle"]],
      ["Une raclette ou une fondue à emporter l'hiver ?", YN],
      ["Tu demandes conseil au fromager ?", ["Toujours", "Parfois", "Jamais"]],
      ["Des fromages d'autres pays, ça te plairait ?", YN],
      ["Un fromage du mois à prix doux ?", YN],
      ["Tu passes plutôt…", ["En semaine", "Le samedi", "Le dimanche matin"]],
      ["Des accompagnements (confitures, pains), ça t'intéresse ?", YN],
      ["Une commande en ligne à retirer, ce serait utile ?", YN],
      ["Une carte de fidélité, ça te motiverait ?", YN],
    ],
  },
  primeur: {
    sector: "Primeur", emoji: "🥕", interest: "commerce",
    names: ["Le Panier de Mirabelle", "Fruits & Lucioles", "Le Potager Rieur", "Primeur Hirondelle", "La Carotte Voyageuse", "Le Verger Bleu", "Primeur Comète", "La Pomme Dorée", "Saveurs du Jardin", "Le Champ d'Armor"],
    desc: "Primeur : fruits et légumes de saison, producteurs locaux et paniers à composer.",
    rewards: ["Fruit de saison offert", "Botte d'herbes offerte", "Petit panier de fruits", "Panier de légumes de saison", "Grand panier fruits et légumes"],
    bank: [
      ["Tu achètes tes fruits et légumes…", ["Chaque semaine", "Plusieurs fois par semaine", "Rarement"]],
      ["Les produits locaux, c'est important ?", ["Très", "Un peu", "Pas vraiment"]],
      ["Un panier de saison à 15 €, ça te paraît…", ["Raisonnable", "Un peu cher", "Trop cher"]],
      ["Un panier hebdomadaire sur abonnement, ça t'intéresse ?", YN],
      ["Le bio, tu le privilégies ?", ["Toujours", "Parfois", "Jamais"]],
      ["Quel fruit exotique aimerais-tu trouver ?", ["Mangue", "Ananas", "Fruit de la passion", "Aucun"]],
      ["Des jus pressés minute, ça te tente ?", YN],
      ["Les fruits « moches » à prix réduit, tu en achèterais ?", YN],
      ["Tu passes plutôt…", ["Le matin", "En fin de journée", "Le week-end"]],
      ["Des recettes de saison affichées en boutique ?", YN],
      ["Une livraison à domicile, ce serait utile ?", YN],
      ["Des légumes déjà préparés (soupes, crudités) ?", YN],
      ["Tu ramènes ton propre sac ou panier ?", ["Toujours", "Parfois", "Jamais"]],
      ["Ce qui compte le plus ?", ["La fraîcheur", "Le prix", "L'origine", "Le choix"]],
      ["Des herbes aromatiques en pot à replanter ?", YN],
      ["Une carte de fidélité, ça te motiverait ?", YN],
    ],
  },
  boucherie: {
    sector: "Boucherie", emoji: "🥩", interest: "commerce",
    names: ["La Boucherie du Tilleul", "Au Bon Couteau", "Boucherie Hirondelle", "Le Billot Doré", "La Côte Voyageuse", "Boucherie Comète", "Le Hachoir Bleu", "Maison Lardon", "Boucherie des Lucioles", "La Boucherie d'Armor"],
    desc: "Boucherie-charcuterie : viandes de producteurs, plats cuisinés maison et conseils de cuisson.",
    rewards: ["Tranche de jambon offerte", "Terrine maison offerte", "Plat cuisiné du jour", "Colis grillades", "Colis familial"],
    bank: [
      ["Tu achètes ta viande…", ["Chaque semaine", "Chaque mois", "Pour les occasions", "Je ne mange pas de viande"]],
      ["L'origine de la viande, c'est important ?", ["Très", "Un peu", "Pas vraiment"]],
      ["Des plats cuisinés maison le midi, ça t'intéresse ?", YN],
      ["Un colis barbecue l'été, ça te tente ?", YN],
      ["Tu demandes des conseils de cuisson ?", ["Souvent", "Parfois", "Jamais"]],
      ["La viande bio, tu la privilégies ?", ["Oui", "Parfois", "Non"]],
      ["Une commande en ligne à retirer, ce serait utile ?", YN],
      ["Quelle charcuterie maison te manque ?", ["Pâté", "Rillettes", "Saucisson", "Jambon blanc"]],
      ["Tu passes plutôt…", ["En semaine", "Le samedi", "Le dimanche matin"]],
      ["Des portions pour une personne, ça t'arrange ?", YN],
      ["Un atelier « bien découper sa volaille » ?", YN],
      ["Un plat du jour à emporter le soir ?", YN],
      ["Ce qui compte le plus ?", ["La qualité", "Le prix", "Le conseil", "Le choix"]],
      ["Des viandes marinées prêtes à cuire ?", YN],
      ["Une volaille rôtie le dimanche, tu la réserverais ?", YN],
      ["Une carte de fidélité, ça te motiverait ?", YN],
    ],
  },
  friperie: {
    sector: "Friperie", emoji: "👕", interest: "commerce",
    names: ["La Fripe Vagabonde", "Seconde Comète", "Le Cintre Rieur", "Fripes & Lucioles", "La Malle Bleue", "Le Grenier Doré", "Fripe Hirondelle", "Le Vestiaire Lunaire", "La Penderie Voyageuse", "Fripes d'Armor"],
    desc: "Friperie : vêtements de seconde main triés, vintage et dépôt-vente.",
    rewards: ["Accessoire offert", "Tote bag offert", "Bon de 10 €", "Vêtement au choix", "Bon de 40 €"],
    bank: [
      ["Tu achètes de la seconde main…", ["Souvent", "Parfois", "Jamais"]],
      ["Ce que tu cherches surtout ?", ["Vestes", "Jeans", "Pulls", "Accessoires"]],
      ["Un jean d'occasion à 15 €, ça te paraît…", ["Raisonnable", "Un peu cher", "Trop cher"]],
      ["Tu déposerais tes vêtements en dépôt-vente ?", YN],
      ["Le vintage des années 90, ça te plaît ?", YN],
      ["Une vente au kilo, ça te tente ?", YN],
      ["Des vêtements pour enfants d'occasion ?", ["Oui", "Peut-être", "Pas concerné"]],
      ["Un atelier retouche et customisation ?", YN],
      ["Ce qui te freine pour acheter d'occasion ?", ["Les tailles", "L'hygiène", "Le choix", "Rien"]],
      ["Tu passes plutôt…", ["En semaine", "Le samedi", "Ça dépend"]],
      ["Les nouveautés annoncées chaque semaine, ça t'aide ?", YN],
      ["Un échange de vêtements entre habitants ?", YN],
      ["Des pièces de créateurs d'occasion, ça t'intéresse ?", YN],
      ["Tu préfères…", ["Fouiller", "Un rayon bien trié", "Les deux"]],
      ["Une cabine d'essayage spacieuse, c'est important ?", ["Très", "Un peu", "Pas du tout"]],
      ["Une carte de fidélité, ça te motiverait ?", YN],
    ],
  },
  pressing: {
    sector: "Pressing", emoji: "👔", interest: "services",
    names: ["Pressing Hirondelle", "Le Cintre Bleu", "Pressing Comète", "Net & Plume", "La Chemise Rieuse", "Pressing du Phare", "Blanc de Lune", "Le Repassage Doré", "Pressing Lucioles", "Pressing d'Iroise"],
    desc: "Pressing écologique : nettoyage, repassage et retouches, service express en 24 h.",
    rewards: ["Repassage d'une chemise", "Nettoyage d'une cravate ou d'un foulard", "Nettoyage d'un pantalon", "Nettoyage d'une veste", "Nettoyage d'une couette"],
    bank: [
      ["Tu utilises un pressing…", ["Chaque semaine", "Chaque mois", "Rarement", "Jamais"]],
      ["Ce que tu y apportes surtout ?", ["Chemises", "Costumes", "Manteaux", "Couettes"]],
      ["Le nettoyage écologique, c'est important ?", ["Très", "Un peu", "Pas vraiment"]],
      ["Un service express en 24 h, ça t'intéresse ?", YN],
      ["Une collecte à domicile, ce serait utile ?", YN],
      ["Des retouches sur place, ça te servirait ?", YN],
      ["Ton créneau idéal pour déposer ?", ["Avant 9h", "Pause déjeuner", "Après 18h", "Le samedi"]],
      ["Un forfait chemises mensuel, ça t'intéresse ?", YN],
      ["Un SMS quand c'est prêt, c'est utile ?", YN],
      ["Une consigne 24 h/24 pour déposer et récupérer ?", YN],
      ["Ce qui compte le plus ?", ["La qualité", "La rapidité", "Le prix", "Les horaires"]],
      ["Le nettoyage de chaussures, ça t'intéresse ?", YN],
      ["Le nettoyage de rideaux ou de tapis ?", YN],
      ["Tu paierais un peu plus pour un résultat parfait ?", YN],
      ["Une carte de fidélité, ça te motiverait ?", YN],
      ["Un ticket de dépôt sur ton téléphone ?", YN],
    ],
  },
  cordonnerie: {
    sector: "Cordonnerie", emoji: "👞", interest: "services",
    names: ["Le Talon Rieur", "Cordonnerie Hirondelle", "La Semelle Bleue", "Clés & Comète", "Le Cuir Voyageur", "Cordonnerie du Phare", "L'Aiguille Dorée", "Le Lacet Lunaire", "Cordonnerie Lucioles", "Le Sabot d'Armor"],
    desc: "Cordonnerie : réparation de chaussures, maroquinerie, double de clés et gravure.",
    rewards: ["Lacets offerts", "Cirage des chaussures", "Double de clé offert", "Talons remplacés", "Ressemelage complet"],
    bank: [
      ["Tu fais réparer tes chaussures ?", ["Souvent", "Parfois", "Jamais"]],
      ["Le service que tu utilises le plus ?", ["Réparation", "Double de clés", "Cirage", "Maroquinerie"]],
      ["Un remplacement de talons à 15 €, ça te paraît…", ["Raisonnable", "Un peu cher", "Trop cher"]],
      ["Une réparation minute pendant que tu attends ?", YN],
      ["La réparation de sacs et de ceintures, ça t'intéresse ?", YN],
      ["Tu préfères réparer plutôt que racheter ?", ["Toujours", "Si c'est possible", "Rarement"]],
      ["La gravure (plaques, médailles), ça te servirait ?", YN],
      ["Ton créneau idéal ?", ["Avant 9h", "Pause déjeuner", "Après 18h", "Le samedi"]],
      ["Un SMS quand c'est prêt, c'est utile ?", YN],
      ["Le nettoyage de baskets, ça te tente ?", YN],
      ["Des conseils pour entretenir tes chaussures ?", YN],
      ["Ce qui compte le plus ?", ["La qualité", "La rapidité", "Le prix", "Le conseil"]],
      ["Le rétrécissement ou l'élargissement de chaussures ?", YN],
      ["Des produits d'entretien en vente, ça t'intéresse ?", YN],
      ["Tu ferais réparer une valise ?", YN],
      ["Une carte de fidélité, ça te motiverait ?", YN],
    ],
  },
  animalerie: {
    sector: "Animalerie", emoji: "🐾", interest: "commerce",
    names: ["Patte de Velours", "L'Arche Comète", "La Gamelle Rieuse", "Croquettes & Lune", "Le Panier Bleu", "Animalerie Hirondelle", "La Patte Dorée", "Le Nid Voyageur", "Plumes & Pattes", "Animalerie d'Armor"],
    desc: "Animalerie de quartier : alimentation, accessoires et conseils pour chiens, chats et petits animaux.",
    rewards: ["Friandise offerte", "Jouet offert", "Sac de croquettes 2 kg", "Toilettage express", "Panier ou coussin au choix"],
    bank: [
      ["Tu as un animal ?", ["Chien", "Chat", "Petit animal", "Pas d'animal"]],
      ["Tu achètes sa nourriture…", ["En animalerie", "En supermarché", "En ligne", "Pas concerné"]],
      ["Des croquettes de qualité, c'est important ?", ["Très", "Un peu", "Pas concerné"]],
      ["Un service de toilettage, ça t'intéresse ?", ["Oui", "Peut-être", "Pas concerné"]],
      ["Une livraison des sacs lourds à domicile ?", YN],
      ["Des conseils pour adopter un animal ?", YN],
      ["Un atelier éducation canine, ça te tente ?", ["Oui", "Peut-être", "Pas concerné"]],
      ["Des produits naturels pour animaux ?", YN],
      ["Un abonnement croquettes livrées chaque mois ?", YN],
      ["Ce qui compte le plus ?", ["Le conseil", "Le prix", "Le choix", "La proximité"]],
      ["Une borne de lavage pour chiens en libre-service ?", YN],
      ["Des accessoires faits localement ?", YN],
      ["Une journée adoption avec une association ?", YN],
      ["Un garde d'animaux pendant tes vacances, ce serait utile ?", ["Oui", "Peut-être", "Pas concerné"]],
      ["Tu passes plutôt…", ["En semaine", "Le samedi", "Ça dépend"]],
      ["Une carte de fidélité, ça te motiverait ?", YN],
    ],
  },
};

module.exports = { TYPES };
