// Accueil façon fil (onglets Questions (puis « À deux pas ») / NOOVA, une carte par question), Messages dans la barre du bas,
// page Récompenses simplifiée (solde, bons, « Tu peux t'offrir », « Bientôt à ta portée »).
process.env.FIRESTORE_EMULATOR_HOST='127.0.0.1:8080';process.env.FIREBASE_AUTH_EMULATOR_HOST='127.0.0.1:9099';process.env.FUNCTIONS_EMULATOR='true';
const puppeteer=require('puppeteer-core');const admin=require(__dirname+'/helpers/admin');
admin.initializeApp({projectId:'noova-366d0'});const db=admin.firestore(),aauth=admin.auth();const {Timestamp}=admin.firestore;
const sleep=ms=>new Promise(r=>setTimeout(r,ms));const SH=process.env.SHOTS_DIR;const shot=async(p,n)=>{if(SH)await p.screenshot({path:SH+'/'+n+'.png'}).catch(()=>{});};
let pass=0,fail=0;const check=(n,ok,x)=>{ok?pass++:fail++;console.log((ok?'PASS ':'FAIL ')+n+(!ok&&x!==undefined?'  -> '+JSON.stringify(x):''));};
const wf=(p,fn,t=30000)=>p.waitForFunction(fn,{timeout:t,polling:200});
const setVal=(p,sel,v)=>p.$eval(sel,(el,v)=>{el.value=v;el.dispatchEvent(new Event('input',{bubbles:true}));},v);
(async()=>{
  await fetch('http://127.0.0.1:8080/emulator/v1/projects/noova-366d0/databases/(default)/documents',{method:'DELETE'});await fetch('http://127.0.0.1:9099/emulator/v1/projects/noova-366d0/accounts',{method:'DELETE'});
  const M=(id,o)=>db.doc('merchants/'+id).set({role:'merchant',ownerUid:id,city:'le-mans',cityLabel:'Le Mans',status:'verified',email:id+'@s.fr',...o});
  await M('m1',{brandName:'Le Fournil',name:'Le Fournil',sector:'Boulangerie',coverUrl:'http://localhost:8950/bg-accueil.svg'});await M('m2',{brandName:'Café Plumes',name:'Café Plumes',sector:'Café'});
  for(const [i,lab,cost,m] of [[1,'Café offert',150,'m2'],[2,'Croissant offert',300,'m1'],[3,'Viennoiserie au choix',500,'m1'],[4,'Menu midi -20 %',900,'m2']])await db.doc('rewards/r'+i).set({merchantId:m,merchantName:m==='m1'?'Le Fournil':'Café Plumes',city:'le-mans',label:lab,tier:i,slot:i,cost,priceConfirmed:true,monthlyQuota:20,timeSlots:[],withPurchase:false,status:'approved',active:true,approved:true,createdAt:Timestamp.now()});
  await db.doc('redemptions/x1').set({userId:'me',merchantId:'m2',merchantName:'Café Plumes',label:'Café offert',cost:150,status:'pending',code:'A7K2',createdAt:Timestamp.now(),expiresAt:Timestamp.fromMillis(Date.now()+86400000)});
  await M('noova',{brandName:'NOOVA',name:'NOOVA',sector:'NOOVA',broadcast:true});
  const C=(id,o)=>db.doc('campaigns/'+id).set({status:'active',targetCity:'le-mans',city:'le-mans',questions:[{q:o.question,format:'mcq',options:['Oui','Non']}],createdAt:Timestamp.now(),...o});
  await C('c1',{merchantId:'m1',merchantName:'Le Fournil',question:'Tu préfères la baguette tradition ou classique ?'});
  await C('c2',{merchantId:'m2',merchantName:'Café Plumes',question:'Tu viendrais pour un brunch le dimanche ?'});
  await C('c3',{merchantId:'noova',merchantName:'NOOVA',question:'Qu\'est-ce qui te ferait revenir chaque jour sur NOOVA ?',targetCity:'toutes',broadcast:true});
  await db.doc('users/me').set({role:'user',name:'Moi',email:'me@t.fr',city:'le-mans',cityLabel:'Le Mans',welcomeClaimed:true,onboardingStep:'done',seenHomeTour:true,authorizedMerchants:['m1','m2','noova'],answeredCampaigns:[],points:120,xp:0,streak:2,ageRange:'25-34',interests:['restauration'],friendUids:[]});
  await aauth.createUser({uid:'me',email:'me@t.fr',password:'secret123'});await sleep(3000);
  const b=await puppeteer.launch({executablePath:process.env.CHROME_PATH,headless:'new',args:['--no-sandbox']});
  const p=await b.newPage();await p.setViewport({width:390,height:844,isMobile:true,hasTouch:true,deviceScaleFactor:2});
  const errs=[];p.on('pageerror',e=>errs.push(e.message));
  await p.goto('http://localhost:8950/app.html',{waitUntil:'load'});await wf(p,()=>document.getElementById('onboard').classList.contains('active'));
  await p.evaluate(()=>showAuthWall('login'));await setVal(p,'#aw-email','me@t.fr');await setVal(p,'#aw-pass','secret123');await p.evaluate(()=>awSubmit());
  await wf(p,()=>document.getElementById('home').classList.contains('active')&&document.querySelectorAll('.hq-card').length>=2);await sleep(1500);
  await shot(p,'home_q');
  const h=await p.evaluate(()=>({tabs:[...document.querySelectorAll('.hm-tab')].map(t=>t.textContent.replace(/\d+/,'').trim()),q:[...document.querySelectorAll('#hm-feed-q .hq-card')].map(c=>c.textContent),legacy:getComputedStyle(document.getElementById('home-legacy')).display,gains:[...document.querySelectorAll('#hm-feed-q .hq-gain')].map(g=>g.textContent),count:document.getElementById('hm-n-q').textContent}));
  check('Accueil : 2 onglets Questions / NOOVA',h.tabs.join()==='Questions,NOOVA',h.tabs);
  check('Onglet Questions : une carte par question de commerce (commerce, question, gain), pas celle de NOOVA',h.q.length===2&&h.q.every(t=>!/NOOVA/.test(t))&&h.q.some(t=>/Le Fournil/.test(t)&&/baguette/.test(t))&&h.gains.every(g=>/\+10 pts/.test(g))&&h.count==='2',h);
  check('Plus de « À répondre », de « prochaine récompense » ni de question du jour séparée',h.legacy==='none'&&!/À répondre|prochaine récompense/.test(await p.evaluate(()=>document.getElementById('home').innerText)));
  await p.evaluate(()=>homeTab('noova'));await sleep(500);await shot(p,'home_noova');
  const n=await p.evaluate(()=>({cards:[...document.querySelectorAll('#hm-feed-noova .hq-card')].map(c=>c.textContent),qHidden:document.getElementById('hm-q').hidden}));
  check('Onglet NOOVA : seulement la question de NOOVA, gain en NOOV',n.cards.length===1&&/NOOVA/.test(n.cards[0])&&/NOOV/.test(n.cards[0])&&n.qHidden,n);
  await p.click('#hm-feed-noova .hq-card');await sleep(700);
  check('Toucher une carte ouvre la question, comme avant',await p.evaluate(()=>cur==='question'&&/revenir chaque jour/.test(document.getElementById('q-text').textContent)));
  await p.evaluate(()=>goNav('home'));await sleep(400);
  await p.evaluate(()=>homeTab('q'));await sleep(500);
  const shops=await p.evaluate(()=>{const f=document.getElementById('hm-feed-q'),m=document.getElementById('dmap-card');return {below:!!(f.compareDocumentPosition(m)&Node.DOCUMENT_POSITION_FOLLOWING)&&m.closest('#hm-q')!==null,n:document.querySelectorAll('#dnearby-grid .dnb-card').length};});
  check('« À deux pas » (carte et commerces) sous toutes les questions, dans l\'onglet Questions',shops.below&&shops.n===2,shops);
  await p.evaluate(()=>document.getElementById('dmap-card').scrollIntoView());await sleep(400);await shot(p,'home_shops');
  await p.evaluate(()=>{document.querySelectorAll('.firebase-emulator-warning').forEach(e=>e.remove());goNav('inbox');});await sleep(600);await shot(p,'nav_inbox');
  check('Messages dans la barre du bas, juste avant Profil',await p.evaluate(()=>{const m=document.getElementById('nav-inbox');return cur==='inbox'&&m.nextElementSibling.id==='nav-profile'&&document.getElementById('bnav').classList.contains('show')&&m.classList.contains('on');}));
  await p.evaluate(()=>goNav('rewards-tab'));await sleep(1500);await shot(p,'rw1');
  const r=await p.evaluate(()=>({h:[...document.querySelectorAll('#rewards-tab .dsec-h')].filter(e=>!e.hidden&&getComputedStyle(e).display!=='none'&&!e.closest('[hidden]')).map(e=>e.textContent.trim()),soon:[...document.querySelectorAll('#rw-soon .rwr')].map(e=>e.textContent.replace(/\s+/g,' ')),code:document.getElementById('dcode-wrap').textContent,legacy:document.getElementById('rw-legacy').hidden,all:document.getElementById('rw-all-btn').textContent}));
  check('Récompenses : solde, « À montrer en caisse », « Tu peux t\'offrir », « Bientôt à ta portée »',r.h.join('|')==='À montrer en caisse|Tu peux t\'offrir|Bientôt à ta portée'&&/A 7 K 2/.test(r.code),r);
  check('« Bientôt à ta portée » : la plus proche en premier, « encore 30 pts », sans pourcentage',/Café offert.*encore 30 pts.*150 pts/.test(r.soon[0])&&!r.soon.slice(0,3).join().includes('%')&&r.legacy,r.soon);
  check('Bouton « Voir toutes les récompenses (4) »',r.all==='Voir toutes les récompenses (4)',r.all);
  await db.doc('users/me').update({points:320});await sleep(1500);await p.evaluate(()=>{S.pts=320;refreshWallet();});await sleep(800);
  const c=await p.evaluate(()=>[...document.querySelectorAll('#rw-can .rwr')].map(e=>e.textContent.replace(/\s+/g,' ')));
  check('Avec 320 points : « Tu peux t\'offrir » liste le croissant et le café, avec « Échanger »',c.length===2&&/Croissant offert/.test(c[0])&&c.every(t=>/Échanger/.test(t)),c);
  await p.evaluate(()=>{const s=document.getElementById('rewards-tab');s.scrollTop=700;});await sleep(400);await shot(p,'rw2');
  await p.evaluate(()=>{const s=document.getElementById('rewards-tab');s.scrollTop=1500;});await sleep(400);
  check('Aucune erreur JavaScript',errs.length===0,errs);
  console.log(`\n${pass} ok, ${fail} échec(s)`);
  await b.close();process.exit(0);
})().catch(e=>{console.log('FAIL '+e);process.exit(1);});
